# Generated by Django 5.2.4 on 2025-08-01 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('titulo', models.CharField(max_length=50)),
                ('contenido', models.TextField()),
                ('resumen', models.TextField(help_text='Breve descripción del artículo', max_length=300)),
                ('imagen_destacada', models.ImageField(blank=True, null=True, upload_to='articulos')),
                ('tags', models.CharField(blank=True, help_text='Separar con comas', max_length=200)),
            ],
        ),
    ]
